name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4.0.2
      #   with:
      #     node-version: 20
      # - run: yarn
      # - run: yarn run test

      - name: Generate commit tag
        id: generate_commit_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "::set-output name=sha::$SHA"

      - run: echo "${{steps.generate_commit_tag.outputs.sha}}"

      # - name: Build docker image
      #   run: docker build -t my-ci-api:${{ steps.generate_commit_tag.outputs.sha }} .
