name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Setup Node.js environment | ${{matrix.node}}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{matrix.node}}
          cache: 'yarn'
      - run: yarn
      - run: yarn run test
