name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: yarn
      - run: yarn run test

      - name: Generate commit tag
        id: generate_commit_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "::set-output name=sha::$SHA"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE }}
          aws-region: us-east-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker image to Amazon ECR
        id: build-docker-image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: rocketseat_ci
          IMAGE_TAG: ${{ steps.generate_commit_tag.outputs.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          IMAGE=$(echo $$REGISTRY/$REPOSITORY:$IMAGE_TAG)
          echo "::set-output name=image::$IMAGE"

      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: rocketseat_api
          image: ${{ steps.build-docker-image.outputs.image }}
          access-role-arn: ${{ secrets.APP_RUNNER_ROLE }}
          region: us-east-2
          cpu: 1
          memory: 2
          port: 3000

      # - name: Login into Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push docker image on Docker Hub
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: marcosparreiras/my-ci-api:${{ steps.generate_commit_tag.outputs.sha }},marcosparreiras/my-ci-api:latest

      ##   Build and push on Docker Hub without actions
      # - name: Build docker image
      #   run: docker build -t marcosparreiras/my-ci-api:${{ steps.generate_commit_tag.outputs.sha }} .

      # - name: Push image
      #   run: docker push marcosparreiras/my-ci-api:${{ steps.generate_commit_tag.outputs.sha }}
